### ISSUE TITLE
Sonoma Bug: Enabled Yubiswitch menubar icon is 10x size

### ISSUE THREAD

**Issue by octoxan** [pallotron/yubiswitch#129]
When you hit "Enable Yubikey" in the menubar item for Yubiswitch, the icon becomes about 5-10x the size and is really jarring.

![image](https://github.com/pallotron/yubiswitch/assets/4382195/b1417cf5-e56d-442e-a34c-36ab589c8485)

**Comment by ludokx** [comment]
Thanks for the quick merge @davidrothera! Do you have an idea when the next release would be by chance? This bug is not a huge deal but it is a bit jarring indeed, especially when using the yubikey multiple times a day ;p

**Comment by davidrothera** [comment]
Releases are a bit of a pain but I'll go through and try and get one signed and uploaded tonight.

**Comment by ludokx** [comment]
> Releases are a bit of a pain but I'll go through and try and get one signed and uploaded tonight.

Awesome, thanks @davidrothera! Not urgent but would definitely appreciate it :)

**Comment by davidrothera** [comment]
@ludokx so it looks like its bad news at the moment.

Sonoma requires Xcode 15 and trying to build an archive build against that toolchain is failing due to an issue in the `ShortcutRecorder` library which we use.

Updating `ShortcutRecorder` to a later version also removes the `PTHotKey` framework which we use for some of the hotkey support.

Long story short is that its not as simple as building a new version and releasing it, it looks like this is going to need significant work to update and that is something which I know I don't have at the moment (baby due this week) and I doubt @pallotron has either sadly.

I think rather than trying to apply patches on top of the current code it might be worth building a modern ground-up version of yubiswitch with Swift (and SwiftUI) as I think that will make it easier to maintain into the future.

**Comment by davidrothera** [comment]
FWIW it seems that the support for XPC in Swift has improved a lot since I looked at it last and the later versions of ShortcutRecorder also have good Swift support

https://github.com/Kentzo/ShortcutRecorder
https://github.com/richardnees/Swift-macOS-XPC-Example

I can't make any promises on working on this however being able to rewrite in Swift would be a lot easier than maintaining C/Obj-C 😛

**Comment by ludokx** [comment]
Ha yes I ran into that as I was trying to build locally 😬 Agreed on SwiftUI, would be more able to help with that as well, unfortunately don't have too much time to help with the rewrite.

Focus on family first and get some sleep while you still can 😜

**Comment by KeithMcD** [comment]
A glass-half-full perspective on this bug is that it makes it VERY obvious if your Yubikey is still enabled.

Good luck on the bug fix and congrats on the baby!

**Comment by micahwalter** [comment]
Any update on this? Please let me know if I can help somehow. Would love to see "normal" icon in my menubar ;)
