### ISSUE TITLE
Helper application always required to install

### ISSUE THREAD

**Issue by bmorgenthaler** [pallotron/yubiswitch#36]
Each time I start yubiswitch it requests to install the helper application even though it is still in /Library/PrivilegedHelperTools

**Comment by pallotron** [comment]
yeah this is a thing I'm looking at, I'm using `SMJobBless` API which is not very well documented, there is a nice discussion [here](http://www.cocoabuilder.com/archive/cocoa/309298-question-about-smjobbless.html) with suggestinos on how to check bundle ids/version of the helpers so that you can ask password only when you need to install/update it.

**Comment by pallotron** [comment]
OK this seems to be working well :-)
I will keep it using on my personal laptop for a while to iron out any issue that might occur, after that I will make a new dmg release.

**Comment by pallotron** [comment]
this is issued in releases >=0.9
