### ISSUE TITLE
Yubiswitch 0.12 not working on USB-C key with MacOS 10.13.6

### ISSUE THREAD

**Issue by lightningrob** [pallotron/yubiswitch#82]
Installed Yubiswitch on my Mac and it has no effect on the Yubikey.  Whether the status shows enabled or disabled, pressing the Yubikey always spits out the key string.  Tried rebooting the app to no effect.
Appreciate any tips to debug this.  It seems to work for other Mac users in my group, though they may have older Macs.  Mine is the USB-C version of the key.  Does Yubiswitch support USB-C?

**Comment by pallotron** [comment]
you probably need to change settings (product id, vendor id) to match your device, check instructions in README.md

**Comment by wolftrouble** [comment]
Since this issue is still listed as open: I have the same problem (USB-C key) but I'm running 10.14 (Mojave). I verified my product ID and vendor ID are correct (and unchanged). It used to work for awhile but I'm not sure when stopped; I *think* it stopped working sometime before I switched to Mojave. The problem is I don't bump the key often enough to know, just one day it seemed to no longer be disabled, and that persists to this day.

**Comment by lightningrob** [comment]
Just to update, the steps worked to resolve the issue for me, I can toggle Yubikey on and off now.  Also upgraded to Mojave and didn't encounter any issues.  Feel free to close the ticket unless you want to keep it open for @wolftrouble.
