### ISSUE TITLE
reset switch off timer after YubiKey press

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [pallotron/yubiswitch#94]
Currently the switch off timer starts YubiKey is enabled. Having an option to reset the timer every time YubiKey is pressed so it gets switched off if it hasn't been used for x seconds.

This would make it a lot more convenient to avoid multiple manual enable to finish some tasks.

**Comment by davidrothera** [comment]
I don't *believe* there is way to know when the key has been pressed and especially with new (e.g. FIDO) use cases where the key doesn't even act as a keyboard anymore.

I think is is by design but happy to be corrected. Please re-open if you find any pointers to receiving events that the key has been activated.
